//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameCLGT.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADV
    {
        public System.Guid ID { get; set; }
        public string ADV_name { get; set; }
        public string ADV_image { get; set; }
        public string ADV_link { get; set; }
        public string ADV_description { get; set; }
    }
}
