//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameCLGT.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public System.Guid ID { get; set; }
        public string Game_name { get; set; }
        public string Game_link { get; set; }
        public string Game_detail { get; set; }
        public string Game_description { get; set; }
        public Nullable<double> Game_rate { get; set; }
        public string Game_image { get; set; }
        public int Game_countPlay { get; set; }
        public Nullable<int> Game_KPIpoint { get; set; }
        public Nullable<int> Game_KPIexp { get; set; }
    
        public virtual History History { get; set; }
        public virtual List_game_cate List_game_cate { get; set; }
        public virtual List_type_game List_type_game { get; set; }
        public virtual Vote Vote { get; set; }
    }
}
