//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameCLGT.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public System.Guid ID { get; set; }
        public string User_name { get; set; }
        public string User_id { get; set; }
        public string User_pass { get; set; }
        public string User_email { get; set; }
        public string User_phone { get; set; }
        public string User_avatar { get; set; }
        public Nullable<int> User_point { get; set; }
        public Nullable<int> User_level { get; set; }
    
        public virtual History History { get; set; }
        public virtual Vote Vote { get; set; }
    }
}
