//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameCLGT.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vote
    {
        public System.Guid ID { get; set; }
        public string ID_game { get; set; }
        public string ID_user { get; set; }
        public double Vote_rate { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual User User { get; set; }
    }
}
